spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://localhost:3306/menudb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/menudb
    username: root
    password: mariadb
# fatal -> error -> warn -> info -> debug -> trace
# fatal: 애플리케이션이 동작하지 않는 아주 심각한 경우
# error: 처리 가능하지만 향후 시스템 에러의 원인 가능
# info: 로그인, 상태변경과 같은 정보성 메세지
# debug: 개발 시 디버그 용도로 사용한 메세지
# trace: 디버그 레벨이 광범위할 경우 좀 더 상세한 상태 확인용
  level:
#    root: warn
# 두칸 씩 띄움
    com:
      heanin:
        mybatisspring:
          section01:
            factorybean: debug
